apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  hackers-api:
    if: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-api']['cloudbeesdemo/PROJECT_NAME-api'].deploy }}
    uses: TARGET_ORG/PROJECT_NAME-api/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-api']['cloudbeesdemo/PROJECT_NAME-api'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-api']['cloudbeesdemo/PROJECT_NAME-api'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
  hackers-auth:
    if: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-auth']['cloudbeesdemo/PROJECT_NAME-auth'].deploy }}
    uses: TARGET_ORG/PROJECT_NAME-auth/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-auth']['cloudbeesdemo/PROJECT_NAME-auth'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-auth']['cloudbeesdemo/PROJECT_NAME-auth'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
  hackers-web:
    if: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-web']['cloudbeesdemo/PROJECT_NAME-web'].deploy }}
    uses: TARGET_ORG/PROJECT_NAME-web/.cloudbees/workflows/deploy.yaml
    with:
      artifactVersion: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-web']['cloudbeesdemo/PROJECT_NAME-web'].version }}
      artifact-id: ${{ fromJSON(inputs.manifest)['PROJECT_NAME-web']['cloudbeesdemo/PROJECT_NAME-web'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
